spring:
  datasource:
    url: jdbc:mysql://106.15.248.46:3306/wkl?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    #url: jdbc:mysql://localhost:3306/wkl?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver